name: XGuardian Scanning Workflow

on:
  push:
    branches:
      - main

jobs:
  xguardian-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: XGuardian Scanning
        uses: ./.github/actions/xguardian-actions # https://github.com/xmart-xguardian/xguardian-actions
        with:
          api_email: ${{ secrets.API_EMAIL }}
          api_password: ${{ secrets.API_PASSWORD }}
          api_token: ${{ secrets.API_TOKEN }}
          gh_token: ${{ secrets.GH_TOKEN }}
          app_name: ${{ github.event.repository.name }}
          team_id: '[1]'
          languages: '["JavaScript"]'
          description: "Aplicação criada através do GitHub Actions - XGuardian"
          policy_sast: '0'
          policy_sca: '0'
          policy_dast: '0'
          policy_container: '0'
          microservices: "false"
          microservices_data: '[{"name": "MS1", "language": ["JavaScript"]}]'
          sast: "true"
          sca: "false"
          translate: "false"
          exclude: ""
          pdf: "false"
          save_vulns: "false"